import { Receipt } from "@/types/invoice";
import { InvoiceTemplate } from "@/types/invoice";

interface ReceiptPreviewProps {
  receipt: Receipt;
  template: InvoiceTemplate;
}

export const ReceiptPreview = ({ receipt, template }: ReceiptPreviewProps) => {
  const { branding, styling } = template;

  const fontClass = {
    inter: "font-sans",
    serif: "font-serif",
    mono: "font-mono",
  }[styling.fontFamily];

  return (
    <div className={`w-full max-w-sm mx-auto p-6 bg-white ${fontClass}`}>
      {/* Header */}
      <div className="text-center mb-4 pb-4 border-b-2" style={{ borderColor: styling.primaryColor }}>
        {styling.showLogo && branding.companyLogo && (
          <img
            src={branding.companyLogo}
            alt="Company Logo"
            className="h-12 mx-auto mb-2 object-contain"
          />
        )}
        <h1 className="text-xl font-bold mb-1" style={{ color: styling.primaryColor }}>
          {branding.companyName}
        </h1>
        {branding.companyAddress && (
          <p className="text-xs text-gray-600">{branding.companyAddress}</p>
        )}
        {branding.companyPhone && (
          <p className="text-xs text-gray-600">{branding.companyPhone}</p>
        )}
      </div>

      {/* Receipt Info */}
      <div className="mb-4 text-center">
        <h2 className="text-2xl font-bold mb-2" style={{ color: styling.accentColor }}>
          RECEIPT
        </h2>
        <p className="text-sm font-semibold">{receipt.receiptNumber}</p>
        <p className="text-xs text-gray-600">{receipt.date}</p>
        {receipt.customerName && (
          <p className="text-sm mt-2">Customer: {receipt.customerName}</p>
        )}
      </div>

      {/* Items */}
      <div className="mb-4">
        <div className="space-y-2">
          {receipt.items.map((item, index) => (
            <div key={index} className="flex justify-between text-sm py-1 border-b border-gray-200">
              <div className="flex-1">
                <span className="font-medium">{item.name}</span>
                <span className="text-gray-600 ml-2">×{item.quantity}</span>
              </div>
              <span className="font-semibold">${(item.quantity * item.price).toFixed(2)}</span>
            </div>
          ))}
        </div>

        {/* Total */}
        <div className="mt-4 pt-3 border-t-2" style={{ borderColor: styling.primaryColor }}>
          <div className="flex justify-between items-center">
            <span className="text-lg font-bold">TOTAL:</span>
            <span className="text-2xl font-bold" style={{ color: styling.primaryColor }}>
              ${receipt.total.toFixed(2)}
            </span>
          </div>
          <p className="text-xs text-gray-600 text-right mt-1">
            Paid by {receipt.paymentMethod}
          </p>
        </div>
      </div>

      {/* Notes */}
      {receipt.notes && (
        <div className="mb-4 text-center text-xs text-gray-600 border-t pt-3">
          <p>{receipt.notes}</p>
        </div>
      )}

      {/* Footer */}
      <div className="text-center text-xs text-gray-500 pt-3 border-t">
        <p>Thank you for your business!</p>
        {styling.showWatermark && (
          <p className="mt-1 text-gray-400">Generated by Business Manager</p>
        )}
      </div>
    </div>
  );
};
